runtime: python310
entrypoint: gunicorn -b :$PORT backend.main:app

#[START env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
  DB_STRING: >
    postgresql+psycopg2://postgres:cs373idb@/postgres?host=/cloudsql/coddle-463619:us-central1:fishingdb
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
  cloud_sql_instances: coddle-463619:us-central1:fishingdb

# API routes handled by Flask (FIRST) & Frontend Routes from frontend/dist
handlers:
  - url: /api/.*
    script: auto

  - url: /static
    static_dir: backend/static
  
  # Serve static folders from Vite build
  - url: /assets
    static_dir: frontend/dist/assets

  - url: /data
    static_dir: frontend/dist/data

  - url: /images
    static_dir: frontend/dist/images

  - url: /videos
    static_dir: frontend/dist/videos

  # Serve specific static files
  - url: /logo\.svg
    static_files: frontend/dist/logo.svg
    upload: frontend/dist/logo\.svg

  # Serve index.html for all other frontend routes (client-side routing)
  - url: /
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html

  - url: /.*
    static_files: frontend/dist/index.html
    upload: frontend/dist/index.html