# use: $ docker compose up

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev","--", "--host"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - ENV=production
    command: ["python", "main.py"]
